spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fabricmanager?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    static-path-pattern: /statics/**
  resources:
    static-locations: classpath:statics
server:
  ssl:
    enabled: false
  port: 8081
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.shijinshi.dao.entity
external:
  fabric-ca-server: /fabric-ca-server/
  resources:
    temp: /resources/temp/
    fabricca: /resources/ca/
    docker-certs: /resources/docker-certs/
    scripts: /resources/scripts/
fabric:
  submit-tx:
    wait-time: 30000
  channel:
    manage:
      chaincode: mmcc